[tool.pyright]
include=["parser_cli"]
typeCheckingMode = "strict"
reportUnknownMemberType = "none"
reportUnknownVariableType = "none"
reportUnknownArgumentType = "none"
reportUnknownParameterType = "none"
reportUnknownLambdaType = "none"
reportMissingTypeArgument = "none"
reportMissingTypeStubs = "none"

# black - auto formatting
[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

# flake8 - linting
[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "E701"] # https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.djlint]
ignore="H021"